import '../l10n/app_localizations.dart';

// Ids are strings, so a switch cannot be checked for every id at compile
// time: a test checks that each achievement and skin has its texts.
// An id without texts shows the id itself.

String achievementTitle(String id, AppLocalizations l10n) => switch (id) {
  'klondike.firstWin' => l10n.achievementKlondikeFirstWinTitle,
  'klondike.wins10' => l10n.achievementKlondikeWins10Title,
  'klondike.wins50' => l10n.achievementKlondikeWins50Title,
  'klondike.draw3Win' => l10n.achievementKlondikeDraw3WinTitle,
  'klondike.fastWin' => l10n.achievementKlondikeFastWinTitle,
  'klondike.noUndoWin' => l10n.achievementKlondikeNoUndoWinTitle,
  'klondike.streak3' => l10n.achievementKlondikeStreak3Title,
  'klondike.hardWin' => l10n.achievementKlondikeHardWinTitle,
  'freecell.firstWin' => l10n.achievementFreecellFirstWinTitle,
  'freecell.wins10' => l10n.achievementFreecellWins10Title,
  'freecell.hardWin' => l10n.achievementFreecellHardWinTitle,
  'freecell.noUndoWin' => l10n.achievementFreecellNoUndoWinTitle,
  'freecell.oneCellWin' => l10n.achievementFreecellOneCellWinTitle,
  'freecell.fastWin' => l10n.achievementFreecellFastWinTitle,
  'spider.firstWin' => l10n.achievementSpiderFirstWinTitle,
  'spider.twoSuitsWin' => l10n.achievementSpiderTwoSuitsWinTitle,
  'spider.fourSuitsWin' => l10n.achievementSpiderFourSuitsWinTitle,
  'spider.wins10' => l10n.achievementSpiderWins10Title,
  'spider.noUndoWin' => l10n.achievementSpiderNoUndoWinTitle,
  'spider.streak3' => l10n.achievementSpiderStreak3Title,
  'tripeaks.firstWin' => l10n.achievementTripeaksFirstWinTitle,
  'tripeaks.wins10' => l10n.achievementTripeaksWins10Title,
  'tripeaks.hardWin' => l10n.achievementTripeaksHardWinTitle,
  'tripeaks.run10' => l10n.achievementTripeaksRun10Title,
  'tripeaks.stock10Win' => l10n.achievementTripeaksStock10WinTitle,
  'tripeaks.noUndoWin' => l10n.achievementTripeaksNoUndoWinTitle,
  'mahjong.firstWin' => l10n.achievementMahjongFirstWinTitle,
  'mahjong.turtleWin' => l10n.achievementMahjongTurtleWinTitle,
  'mahjong.hardWin' => l10n.achievementMahjongHardWinTitle,
  'mahjong.noHintWin' => l10n.achievementMahjongNoHintWinTitle,
  'mahjong.combo10' => l10n.achievementMahjongCombo10Title,
  'mahjong.wins10' => l10n.achievementMahjongWins10Title,
  'mahjong.trayWin' => l10n.achievementMahjongTrayWinTitle,
  'mahjong.trayHardWin' => l10n.achievementMahjongTrayHardWinTitle,
  'mahjong.trayNoUndoWin' => l10n.achievementMahjongTrayNoUndoWinTitle,
  'mahjong.trayWins10' => l10n.achievementMahjongTrayWins10Title,
  'minesweeper.firstWin' => l10n.achievementMinesweeperFirstWinTitle,
  'minesweeper.intermediateWin' =>
    l10n.achievementMinesweeperIntermediateWinTitle,
  'minesweeper.expertWin' => l10n.achievementMinesweeperExpertWinTitle,
  'minesweeper.fastWin' => l10n.achievementMinesweeperFastWinTitle,
  'minesweeper.noFlagWin' => l10n.achievementMinesweeperNoFlagWinTitle,
  'minesweeper.wins10' => l10n.achievementMinesweeperWins10Title,
  'all.everyGame' => l10n.achievementAllEveryGameTitle,
  'all.wins100' => l10n.achievementAllWins100Title,
  'all.hours10' => l10n.achievementAllHours10Title,
  _ => id,
};

String achievementDescription(String id, AppLocalizations l10n) => switch (id) {
  'klondike.firstWin' => l10n.achievementKlondikeFirstWinDescription,
  'klondike.wins10' => l10n.achievementKlondikeWins10Description,
  'klondike.wins50' => l10n.achievementKlondikeWins50Description,
  'klondike.draw3Win' => l10n.achievementKlondikeDraw3WinDescription,
  'klondike.fastWin' => l10n.achievementKlondikeFastWinDescription,
  'klondike.noUndoWin' => l10n.achievementKlondikeNoUndoWinDescription,
  'klondike.streak3' => l10n.achievementKlondikeStreak3Description,
  'klondike.hardWin' => l10n.achievementKlondikeHardWinDescription,
  'freecell.firstWin' => l10n.achievementFreecellFirstWinDescription,
  'freecell.wins10' => l10n.achievementFreecellWins10Description,
  'freecell.hardWin' => l10n.achievementFreecellHardWinDescription,
  'freecell.noUndoWin' => l10n.achievementFreecellNoUndoWinDescription,
  'freecell.oneCellWin' => l10n.achievementFreecellOneCellWinDescription,
  'freecell.fastWin' => l10n.achievementFreecellFastWinDescription,
  'spider.firstWin' => l10n.achievementSpiderFirstWinDescription,
  'spider.twoSuitsWin' => l10n.achievementSpiderTwoSuitsWinDescription,
  'spider.fourSuitsWin' => l10n.achievementSpiderFourSuitsWinDescription,
  'spider.wins10' => l10n.achievementSpiderWins10Description,
  'spider.noUndoWin' => l10n.achievementSpiderNoUndoWinDescription,
  'spider.streak3' => l10n.achievementSpiderStreak3Description,
  'tripeaks.firstWin' => l10n.achievementTripeaksFirstWinDescription,
  'tripeaks.wins10' => l10n.achievementTripeaksWins10Description,
  'tripeaks.hardWin' => l10n.achievementTripeaksHardWinDescription,
  'tripeaks.run10' => l10n.achievementTripeaksRun10Description,
  'tripeaks.stock10Win' => l10n.achievementTripeaksStock10WinDescription,
  'tripeaks.noUndoWin' => l10n.achievementTripeaksNoUndoWinDescription,
  'mahjong.firstWin' => l10n.achievementMahjongFirstWinDescription,
  'mahjong.turtleWin' => l10n.achievementMahjongTurtleWinDescription,
  'mahjong.hardWin' => l10n.achievementMahjongHardWinDescription,
  'mahjong.noHintWin' => l10n.achievementMahjongNoHintWinDescription,
  'mahjong.combo10' => l10n.achievementMahjongCombo10Description,
  'mahjong.wins10' => l10n.achievementMahjongWins10Description,
  'mahjong.trayWin' => l10n.achievementMahjongTrayWinDescription,
  'mahjong.trayHardWin' => l10n.achievementMahjongTrayHardWinDescription,
  'mahjong.trayNoUndoWin' => l10n.achievementMahjongTrayNoUndoWinDescription,
  'mahjong.trayWins10' => l10n.achievementMahjongTrayWins10Description,
  'minesweeper.firstWin' => l10n.achievementMinesweeperFirstWinDescription,
  'minesweeper.intermediateWin' =>
    l10n.achievementMinesweeperIntermediateWinDescription,
  'minesweeper.expertWin' => l10n.achievementMinesweeperExpertWinDescription,
  'minesweeper.fastWin' => l10n.achievementMinesweeperFastWinDescription,
  'minesweeper.noFlagWin' => l10n.achievementMinesweeperNoFlagWinDescription,
  'minesweeper.wins10' => l10n.achievementMinesweeperWins10Description,
  'all.everyGame' => l10n.achievementAllEveryGameDescription,
  'all.wins100' => l10n.achievementAllWins100Description,
  'all.hours10' => l10n.achievementAllHours10Description,
  _ => id,
};

String cardBackName(String id, AppLocalizations l10n) => switch (id) {
  'classic' => l10n.cardBackClassic,
  'crimson' => l10n.cardBackCrimson,
  'emerald' => l10n.cardBackEmerald,
  'ocean' => l10n.cardBackOcean,
  'sunset' => l10n.cardBackSunset,
  'midnight' => l10n.cardBackMidnight,
  'royal' => l10n.cardBackRoyal,
  'gold' => l10n.cardBackGold,
  'obsidian' => l10n.cardBackObsidian,
  'azure' => l10n.cardBackAzure,
  'circuit' => l10n.cardBackCircuit,
  'labyrinth' => l10n.cardBackLabyrinth,
  'ivory' => l10n.cardBackIvory,
  'zen' => l10n.cardBackZen,
  'lightning' => l10n.cardBackLightning,
  'web' => l10n.cardBackWeb,
  'twilight' => l10n.cardBackTwilight,
  'venom' => l10n.cardBackVenom,
  'silk' => l10n.cardBackSilk,
  'steel' => l10n.cardBackSteel,
  'amber' => l10n.cardBackAmber,
  'peaks' => l10n.cardBackPeaks,
  'sunrise' => l10n.cardBackSunrise,
  'aurora' => l10n.cardBackAurora,
  'ember' => l10n.cardBackEmber,
  'mosaic' => l10n.cardBackMosaic,
  'tide' => l10n.cardBackTide,
  'prism' => l10n.cardBackPrism,
  'platinum' => l10n.cardBackPlatinum,
  'cosmos' => l10n.cardBackCosmos,
  _ => id,
};

String tileStyleName(String id, AppLocalizations l10n) => switch (id) {
  'classic' => l10n.tileStyleClassic,
  'jade' => l10n.tileStyleJade,
  'bamboo' => l10n.tileStyleBamboo,
  'ebony' => l10n.tileStyleEbony,
  'coral' => l10n.tileStyleCoral,
  'sapphire' => l10n.tileStyleSapphire,
  'golden' => l10n.tileStyleGolden,
  'porcelain' => l10n.tileStylePorcelain,
  'midnight' => l10n.tileStyleMidnight,
  'marble' => l10n.tileStyleMarble,
  'sakura' => l10n.tileStyleSakura,
  _ => id,
};

String minesweeperThemeName(String id, AppLocalizations l10n) => switch (id) {
  'classic' => l10n.minesweeperThemeClassic,
  'ocean' => l10n.minesweeperThemeOcean,
  'meadow' => l10n.minesweeperThemeMeadow,
  'lava' => l10n.minesweeperThemeLava,
  'candy' => l10n.minesweeperThemeCandy,
  'night' => l10n.minesweeperThemeNight,
  'retro' => l10n.minesweeperThemeRetro,
  _ => id,
};
