// Generates lib/games/freecell/freecell_deals.dart: deal seeds that the
// solver proved winnable, by difficulty.
//
//   dart run tool/generate_freecell_deals.dart              # writes the file
//   dart run tool/generate_freecell_deals.dart --stats 1000 # grades seeds
//       1..1000 and prints the distribution (no file)
//
// Seeds are graded in parallel isolates, then taken in seed order, so the
// output does not depend on the number of cores.

// A command-line tool: printing is its output.
// ignore_for_file: avoid_print

import 'dart:io';
import 'dart:isolate';

import 'package:all_for_games/games/freecell/freecell_difficulty.dart';
import 'package:all_for_games/games/freecell/freecell_solver.dart';
import 'package:all_for_games/games/freecell/freecell_state.dart';

const seedsPerBucket = 400;
const _chunkSize = 10;

typedef SeedReport = ({
  int seed,
  bool greedyWins,

  /// Null when the solver was skipped (only easy deals were still needed).
  SolveStatus? status,
  int nodes,
  int moves,

  /// The search with `FreeCellGrading.mediumCells` free cells; null when it
  /// did not run.
  SolveStatus? fewCellsStatus,
  int fewCellsNodes,

  /// The solution replayed to a win on [FreeCellState].
  bool verified,
  FreeCellDifficulty? difficulty,
});

Future<void> main(List<String> args) async {
  final stats = args.indexOf('--stats');
  if (stats >= 0) {
    await _printStats(int.parse(args[stats + 1]));
    return;
  }

  final stopwatch = Stopwatch()..start();
  final deals = await _collect(stopwatch);
  final file = File.fromUri(
    Platform.script.resolve('../lib/games/freecell/freecell_deals.dart'),
  );
  file.writeAsStringSync(_render(deals));
  final format = Process.runSync(Platform.resolvedExecutable, [
    'format',
    file.path,
  ]);
  if (format.exitCode != 0) stderr.write(format.stderr);
  print('Wrote ${file.path} in ${_seconds(stopwatch)}.');
}

/// Grades seeds from 1 upward until every bucket has [seedsPerBucket] seeds.
Future<Map<FreeCellDifficulty, List<int>>> _collect(Stopwatch stopwatch) async {
  final buckets = {for (final d in FreeCellDifficulty.values) d: <int>[]};
  final graded = <SeedReport>[];
  final workers = Platform.numberOfProcessors;
  var next = 1;
  bool full(FreeCellDifficulty d) => buckets[d]!.length >= seedsPerBucket;

  while (!FreeCellDifficulty.values.every(full)) {
    // Once medium and hard are full, only deals the greedy player wins are
    // still worth solving.
    final solveAll =
        !full(FreeCellDifficulty.medium) || !full(FreeCellDifficulty.hard);
    final batch = await Future.wait([
      for (var w = 0; w < workers; w++) _spawn(next + w * _chunkSize, solveAll),
    ]);
    next += workers * _chunkSize;
    for (final report in batch.expand((reports) => reports)) {
      if (report.status != null && solveAll) graded.add(report);
      final difficulty = report.difficulty;
      if (difficulty == null || full(difficulty)) continue;
      if (!report.verified) {
        throw StateError('Seed ${report.seed}: the solution does not replay');
      }
      buckets[difficulty]!.add(report.seed);
    }
    final counts = [
      for (final MapEntry(:key, :value) in buckets.entries)
        '${key.name} ${value.length}',
    ];
    stdout.write(
      '\rseeds 1..${next - 1}, ${counts.join(', ')} '
      '(${_seconds(stopwatch)})   ',
    );
  }
  stdout.writeln();
  _printSummary(graded, buckets);
  return buckets;
}

Future<List<SeedReport>> _spawn(int from, bool solveAll) =>
    Isolate.run(() => _gradeSeeds(from, solveAll));

List<SeedReport> _gradeSeeds(int from, bool solveAll) => [
  for (var seed = from; seed < from + _chunkSize; seed++)
    _gradeSeed(seed, solveAll),
];

SeedReport _gradeSeed(int seed, bool solveAll) {
  const solver = FreeCellSolver();
  final state = FreeCellState.deal(seed);
  if (!solveAll && solver.playGreedy(state) == null) {
    return (
      seed: seed,
      greedyWins: false,
      status: null,
      nodes: 0,
      moves: 0,
      fewCellsStatus: null,
      fewCellsNodes: 0,
      verified: false,
      difficulty: null,
    );
  }
  final grade = solver.grade(seed);
  final result = grade.result;
  return (
    seed: seed,
    greedyWins: grade.greedyWins,
    status: result.status,
    nodes: result.nodes,
    moves: result.solution.length,
    fewCellsStatus: grade.fewCells?.status,
    fewCellsNodes: grade.fewCells?.nodes ?? 0,
    verified:
        result.isSolved &&
        (replayMoves(state, result.solution)?.isWon ?? false),
    difficulty: grade.difficulty,
  );
}

String _render(Map<FreeCellDifficulty, List<int>> deals) {
  final out = StringBuffer()
    ..writeln('// Generated by tool/generate_freecell_deals.dart. Do not edit.')
    ..writeln('//')
    ..writeln(
      '// Grading (FreeCellGrading), for seeds the solver won (within '
      '${FreeCellGrading.maxNodes}',
    )
    ..writeln('// nodes) and whose solution replayed to a win:')
    ..writeln('// - easy: the greedy player (one move ahead, no undo) wins;')
    ..writeln(
      '// - medium: otherwise, the solver wins with '
      '${FreeCellGrading.mediumCells} free cells only (within',
    )
    ..writeln('//   ${FreeCellGrading.fewCellsMaxNodes} nodes);')
    ..writeln(
      '// - hard: otherwise (no solution with fewer free cells was found).',
    )
    ..writeln()
    ..writeln('/// Winnable seeds for `FreeCellState.deal`, by difficulty')
    ..writeln('/// (`FreeCellDifficulty.name`), in increasing order.')
    ..writeln('const freecellDeals = <String, List<int>>{');
  for (final MapEntry(key: difficulty, value: seeds) in deals.entries) {
    out.writeln("  '${difficulty.name}': [${seeds.join(', ')}],");
  }
  out.writeln('};');
  return out.toString();
}

void _printSummary(
  List<SeedReport> graded,
  Map<FreeCellDifficulty, List<int>> buckets,
) {
  final n = graded.length;
  int count(bool Function(SeedReport) test) => graded.where(test).length;
  String rate(int k) => _percent(k, n);
  print(
    '$n seeds fully graded: '
    'solved ${rate(count((r) => r.status == SolveStatus.solved))}, '
    'unknown ${rate(count((r) => r.status == SolveStatus.unknown))}, '
    'unsolvable ${rate(count((r) => r.status == SolveStatus.unsolvable))}, '
    'greedy wins ${rate(count((r) => r.greedyWins))}, '
    'won with ${FreeCellGrading.mediumCells} cells by the solver when the '
    'greedy player loses '
    '${rate(count((r) => r.fewCellsStatus == SolveStatus.solved))}',
  );
  final bySeed = {for (final r in graded) r.seed: r};
  for (final MapEntry(key: difficulty, value: seeds) in buckets.entries) {
    final reports = [for (final s in seeds) ?bySeed[s]];
    print(
      '  ${difficulty.name.padRight(6)} ${seeds.length} seeds, '
      'natural share ${rate(count((r) => r.difficulty == difficulty))}'
      '${_averages(reports)}',
    );
  }
}

String _averages(List<SeedReport> reports) {
  if (reports.isEmpty) return '';
  double avg(int Function(SeedReport) value) =>
      reports.fold(0, (sum, r) => sum + value(r)) / reports.length;
  final nodes = [for (final r in reports) r.nodes]..sort();
  return ', solver nodes avg ${avg((r) => r.nodes).round()} '
      '(median ${nodes[nodes.length ~/ 2]}), '
      '${avg((r) => r.moves).round()} moves per solution';
}

/// Prints the distribution of grading metrics over seeds 1..[count].
Future<void> _printStats(int count) async {
  final workers = Platform.numberOfProcessors;
  final stopwatch = Stopwatch()..start();
  final reports = <SeedReport>[];
  for (var next = 1; next <= count; next += workers * _chunkSize) {
    final batch = await Future.wait([
      for (var w = 0; w < workers; w++) _spawn(next + w * _chunkSize, true),
    ]);
    reports.addAll(batch.expand((r) => r).where((r) => r.seed <= count));
  }
  final buckets = {
    for (final d in FreeCellDifficulty.values)
      d: [
        for (final r in reports)
          if (r.difficulty == d) r.seed,
      ],
  };
  _printSummary(reports, buckets);
  if (reports.any((r) => r.status == SolveStatus.solved && !r.verified)) {
    print('  SOME SOLUTIONS DO NOT REPLAY');
  }
  for (final greedy in [true, false]) {
    final nodes = [
      for (final r in reports)
        if (r.status == SolveStatus.solved && r.greedyWins == greedy) r.nodes,
    ]..sort();
    if (nodes.isEmpty) continue;
    String at(double p) => '${nodes[((nodes.length - 1) * p).round()]}';
    print(
      '  solver nodes when greedy ${greedy ? 'wins ' : 'loses'}: '
      'p10 ${at(.1)}, p25 ${at(.25)}, p50 ${at(.5)}, p75 ${at(.75)}, '
      'p90 ${at(.9)}, max ${nodes.last}',
    );
  }
  // To tune FreeCellGrading.fewCellsMaxNodes.
  final fewCells = [
    for (final r in reports)
      if (r.fewCellsStatus == SolveStatus.solved) r.fewCellsNodes,
  ];
  String share(int budget) => _percent(
    fewCells.where((nodes) => nodes <= budget).length,
    reports.length,
  );
  final shares = [
    for (final budget in [10000, 20000, 50000, 100000])
      '<=$budget: ${share(budget)}',
  ];
  print(
    '  share of seeds medium with a ${FreeCellGrading.mediumCells}-cell '
    'budget of ${shares.join(', ')}',
  );
  print('  ${_seconds(stopwatch)}');
}

String _percent(int part, int total) =>
    '${(100 * part / total).toStringAsFixed(1)}%';

String _seconds(Stopwatch stopwatch) =>
    '${(stopwatch.elapsedMilliseconds / 1000).toStringAsFixed(1)} s';
