// Generates lib/games/spider/spider_deals.dart: deal seeds that the solver
// proved winnable, for 1, 2 and 4 suits.
//
//   dart run tool/generate_spider_deals.dart               # writes the file
//   dart run tool/generate_spider_deals.dart --stats 200   # solves seeds
//       1..200 of each level and prints the rates (no file)
//   dart run tool/generate_spider_deals.dart --stats 200 --level hard
//
// Seeds are solved in parallel isolates, then taken in seed order, so the
// output does not depend on the number of cores.

// A command-line tool: printing is its output.
// ignore_for_file: avoid_print

import 'dart:io';
import 'dart:isolate';

import 'package:all_for_games/games/spider/spider_difficulty.dart';
import 'package:all_for_games/games/spider/spider_solver.dart';
import 'package:all_for_games/games/spider/spider_state.dart';

/// Seeds to collect per level.
const seedsPerLevel = {
  SpiderDifficulty.easy: 400,
  SpiderDifficulty.medium: 400,
  SpiderDifficulty.hard: 400,
};

/// Node budget of each attempt of the solver, by level.
const maxNodes = SpiderSolver.maxNodesFor;

const _chunkSize = 4;

typedef SeedReport = ({
  int seed,
  SolveStatus status,
  int nodes,
  int moves,
  int milliseconds,

  /// The solution replayed to a win on [SpiderState].
  bool verified,
});

Future<void> main(List<String> args) async {
  final levelArg = args.indexOf('--level');
  final levels = levelArg >= 0
      ? [SpiderDifficulty.values.byName(args[levelArg + 1])]
      : SpiderDifficulty.values;
  final stats = args.indexOf('--stats');
  if (stats >= 0) {
    await _printStats(int.parse(args[stats + 1]), levels);
    return;
  }

  final stopwatch = Stopwatch()..start();
  final deals = <SpiderDifficulty, List<int>>{};
  for (final level in SpiderDifficulty.values) {
    deals[level] = await _collect(level, stopwatch);
  }
  final file = File.fromUri(
    Platform.script.resolve('../lib/games/spider/spider_deals.dart'),
  );
  file.writeAsStringSync(_render(deals));
  final format = Process.runSync(Platform.resolvedExecutable, [
    'format',
    file.path,
  ]);
  if (format.exitCode != 0) stderr.write(format.stderr);
  print('Wrote ${file.path} in ${_seconds(stopwatch)}.');
}

/// Solves seeds from 1 upward until the level has its seeds.
Future<List<int>> _collect(SpiderDifficulty level, Stopwatch stopwatch) async {
  final target = seedsPerLevel[level]!;
  final seeds = <int>[];
  final reports = <SeedReport>[];
  final workers = Platform.numberOfProcessors;
  final start = stopwatch.elapsedMilliseconds;
  var next = 1;
  while (seeds.length < target) {
    final batch = await Future.wait([
      for (var w = 0; w < workers; w++) _spawn(next + w * _chunkSize, level),
    ]);
    next += workers * _chunkSize;
    for (final report in batch.expand((reports) => reports)) {
      if (seeds.length >= target) break;
      reports.add(report);
      if (report.status != SolveStatus.solved) continue;
      if (!report.verified) {
        throw StateError('Seed ${report.seed}: the solution does not replay');
      }
      seeds.add(report.seed);
    }
    stdout.write(
      '\r${level.name}: seeds 1..${reports.last.seed}, ${seeds.length} '
      'proven (${_seconds(stopwatch)})   ',
    );
  }
  stdout.writeln();
  _printSummary(level, reports, stopwatch.elapsedMilliseconds - start);
  return seeds;
}

Future<List<SeedReport>> _spawn(int from, SpiderDifficulty level) =>
    Isolate.run(() => _solveSeeds(from, level));

List<SeedReport> _solveSeeds(int from, SpiderDifficulty level) => [
  for (var seed = from; seed < from + _chunkSize; seed++)
    _solveSeed(seed, level),
];

SeedReport _solveSeed(int seed, SpiderDifficulty level) {
  final stopwatch = Stopwatch()..start();
  final state = SpiderState.deal(seed, level);
  final result = const SpiderSolver().solve(state, maxNodes: maxNodes[level]!);
  return (
    seed: seed,
    status: result.status,
    nodes: result.nodes,
    moves: result.solution.length,
    milliseconds: stopwatch.elapsedMilliseconds,
    verified:
        result.isSolved &&
        (replayMoves(state, result.solution)?.isWon ?? false),
  );
}

String _render(Map<SpiderDifficulty, List<int>> deals) {
  final out = StringBuffer()
    ..writeln('// Generated by tool/generate_spider_deals.dart. Do not edit.')
    ..writeln('//')
    ..writeln('// Seeds that SpiderSolver won and whose solution replayed to a')
    ..writeln(
      '// win, with ${SpiderSolver.defaultAttempts.length} attempts of at most '
      '${[for (final level in SpiderDifficulty.values) '${maxNodes[level]} (${level.name})'].join(', ')}',
    )
    ..writeln('// nodes each.')
    ..writeln()
    ..writeln('/// Winnable seeds for `SpiderState.deal`, by difficulty')
    ..writeln('/// (`SpiderDifficulty.name`), in increasing order.')
    ..writeln('const spiderDeals = <String, List<int>>{');
  for (final MapEntry(key: level, value: seeds) in deals.entries) {
    out.writeln("  '${level.name}': [${seeds.join(', ')}],");
  }
  out.writeln('};');
  return out.toString();
}

void _printSummary(
  SpiderDifficulty level,
  List<SeedReport> reports,
  int milliseconds,
) {
  final n = reports.length;
  int count(bool Function(SeedReport) test) => reports.where(test).length;
  String rate(int k) => _percent(k, n);
  final solved = [
    for (final r in reports)
      if (r.status == SolveStatus.solved) r,
  ];
  double avg(int Function(SeedReport) value) => solved.isEmpty
      ? 0
      : solved.fold(0, (sum, r) => sum + value(r)) / solved.length;
  print(
    '${level.name} (${level.suitCount} suit${level.suitCount > 1 ? 's' : ''}, '
    '${maxNodes[level]} nodes per attempt): $n seeds, '
    'solved ${rate(solved.length)}, '
    'unknown ${rate(count((r) => r.status == SolveStatus.unknown))}, '
    'unsolvable ${rate(count((r) => r.status == SolveStatus.unsolvable))}; '
    'solved in avg ${avg((r) => r.nodes).round()} nodes (all attempts), '
    '${avg((r) => r.moves).round()} moves, '
    '${avg((r) => r.milliseconds).round()} ms; '
    '${(milliseconds / 1000).toStringAsFixed(1)} s',
  );
}

/// Prints the rates of the solver over seeds 1..[count] of [levels].
Future<void> _printStats(int count, List<SpiderDifficulty> levels) async {
  final workers = Platform.numberOfProcessors;
  for (final level in levels) {
    final stopwatch = Stopwatch()..start();
    final reports = <SeedReport>[];
    for (var next = 1; next <= count; next += workers * _chunkSize) {
      final batch = await Future.wait([
        for (var w = 0; w < workers; w++) _spawn(next + w * _chunkSize, level),
      ]);
      reports.addAll(batch.expand((r) => r).where((r) => r.seed <= count));
    }
    _printSummary(level, reports, stopwatch.elapsedMilliseconds);
    if (reports.any((r) => r.status == SolveStatus.solved && !r.verified)) {
      print('  SOME SOLUTIONS DO NOT REPLAY');
    }
    final nodes = [
      for (final r in reports)
        if (r.status == SolveStatus.solved) r.nodes,
    ]..sort();
    if (nodes.isNotEmpty) {
      String at(double p) => '${nodes[((nodes.length - 1) * p).round()]}';
      print(
        '  solver nodes: p50 ${at(.5)}, p75 ${at(.75)}, p90 ${at(.9)}, '
        'max ${nodes.last}',
      );
    }
  }
}

String _percent(int part, int total) =>
    '${(100 * part / total).toStringAsFixed(1)}%';

String _seconds(Stopwatch stopwatch) =>
    '${(stopwatch.elapsedMilliseconds / 1000).toStringAsFixed(1)} s';
