// Generates lib/games/tripeaks/tripeaks_deals.dart: deal seeds that the
// solver proved winnable, by difficulty.
//
//   dart run tool/generate_tripeaks_deals.dart              # writes the file
//   dart run tool/generate_tripeaks_deals.dart --stats 1000 # grades seeds
//       1..1000 and prints the distribution (no file)
//
// Seeds are graded in parallel isolates, then taken in seed order, so the
// output does not depend on the number of cores.

// A command-line tool: printing is its output.
// ignore_for_file: avoid_print

import 'dart:io';
import 'dart:isolate';

import 'package:all_for_games/games/tripeaks/tripeaks_difficulty.dart';
import 'package:all_for_games/games/tripeaks/tripeaks_solver.dart';
import 'package:all_for_games/games/tripeaks/tripeaks_state.dart';

const seedsPerBucket = 150;
const _chunkSize = 20;

typedef SeedReport = ({
  int seed,
  bool greedyWins,
  int casualWins,
  SolveStatus status,
  int nodes,
  int moves,

  /// The solution replayed to a win on [TriPeaksState].
  bool verified,
  TriPeaksDifficulty? difficulty,
});

Future<void> main(List<String> args) async {
  final stats = args.indexOf('--stats');
  if (stats >= 0) {
    await _printStats(int.parse(args[stats + 1]));
    return;
  }

  final stopwatch = Stopwatch()..start();
  final deals = await _collect(stopwatch);
  final file = File.fromUri(
    Platform.script.resolve('../lib/games/tripeaks/tripeaks_deals.dart'),
  );
  file.writeAsStringSync(_render(deals));
  final format = Process.runSync(Platform.resolvedExecutable, [
    'format',
    file.path,
  ]);
  if (format.exitCode != 0) stderr.write(format.stderr);
  print('Wrote ${file.path} in ${_seconds(stopwatch)}.');
}

/// Grades seeds from 1 upward until every bucket has [seedsPerBucket] seeds.
Future<Map<TriPeaksDifficulty, List<int>>> _collect(Stopwatch stopwatch) async {
  final buckets = {for (final d in TriPeaksDifficulty.values) d: <int>[]};
  final graded = <SeedReport>[];
  final workers = Platform.numberOfProcessors;
  var next = 1;
  bool full(TriPeaksDifficulty d) => buckets[d]!.length >= seedsPerBucket;

  while (!TriPeaksDifficulty.values.every(full)) {
    final batch = await Future.wait([
      for (var w = 0; w < workers; w++) _spawn(next + w * _chunkSize),
    ]);
    next += workers * _chunkSize;
    for (final report in batch.expand((reports) => reports)) {
      graded.add(report);
      final difficulty = report.difficulty;
      if (difficulty == null || full(difficulty)) continue;
      if (!report.verified) {
        throw StateError('Seed ${report.seed}: the solution does not replay');
      }
      buckets[difficulty]!.add(report.seed);
    }
    final counts = [
      for (final MapEntry(:key, :value) in buckets.entries)
        '${key.name} ${value.length}',
    ];
    stdout.write(
      '\rseeds 1..${next - 1}, ${counts.join(', ')} '
      '(${_seconds(stopwatch)})   ',
    );
  }
  stdout.writeln();
  _printSummary(graded, buckets);
  return buckets;
}

Future<List<SeedReport>> _spawn(int from) =>
    Isolate.run(() => _gradeSeeds(from));

List<SeedReport> _gradeSeeds(int from) => [
  for (var seed = from; seed < from + _chunkSize; seed++) _gradeSeed(seed),
];

SeedReport _gradeSeed(int seed) {
  final grade = const TriPeaksSolver().grade(seed);
  final result = grade.result;
  return (
    seed: seed,
    greedyWins: grade.greedyWins,
    casualWins: grade.casualWins,
    status: result.status,
    nodes: result.nodes,
    moves: result.solution.length,
    verified:
        result.isSolved &&
        (replayMoves(TriPeaksState.deal(seed), result.solution)?.isWon ??
            false),
    difficulty: grade.difficulty,
  );
}

String _render(Map<TriPeaksDifficulty, List<int>> deals) {
  String percent(double rate) => '${(rate * 100).toStringAsFixed(1)}%';
  final out = StringBuffer()
    ..writeln('// Generated by tool/generate_tripeaks_deals.dart. Do not edit.')
    ..writeln('//')
    ..writeln(
      '// Grading (TriPeaksGrading), for seeds the solver won (within '
      '${TriPeaksGrading.maxNodes}',
    )
    ..writeln('// positions) and whose solution replayed to a win. The greedy')
    ..writeln('// player plays the card that leaves the most cards to play and')
    ..writeln(
      '// draws only when no card fits; the casual player plays a random',
    )
    ..writeln(
      '// card that fits (${TriPeaksGrading.casualGames} games per deal):',
    )
    ..writeln(
      '// - easy: the greedy player wins, the casual player at least '
      '${percent(TriPeaksGrading.easyMinWinRate)};',
    )
    ..writeln(
      '// - medium: the greedy player loses, the casual player wins '
      '${percent(TriPeaksGrading.mediumMinWinRate)} to '
      '${percent(TriPeaksGrading.mediumMaxWinRate)};',
    )
    ..writeln(
      '// - hard: the greedy player loses, the casual player wins '
      '${percent(TriPeaksGrading.hardMinWinRate)} to '
      '${percent(TriPeaksGrading.hardMaxWinRate)}.',
    )
    ..writeln()
    ..writeln('/// Winnable seeds for `TriPeaksState.deal`, by difficulty')
    ..writeln('/// (`TriPeaksDifficulty.name`), in increasing order.')
    ..writeln('const triPeaksDeals = <String, List<int>>{');
  for (final MapEntry(key: difficulty, value: seeds) in deals.entries) {
    out.writeln("  '${difficulty.name}': [${seeds.join(', ')}],");
  }
  out.writeln('};');
  return out.toString();
}

void _printSummary(
  List<SeedReport> graded,
  Map<TriPeaksDifficulty, List<int>> buckets,
) {
  final n = graded.length;
  int count(bool Function(SeedReport) test) => graded.where(test).length;
  String rate(int k) => _percent(k, n);
  print(
    '$n seeds graded: '
    'solved ${rate(count((r) => r.status == SolveStatus.solved))}, '
    'unknown ${rate(count((r) => r.status == SolveStatus.unknown))}, '
    'unsolvable ${rate(count((r) => r.status == SolveStatus.unsolvable))}, '
    'greedy wins ${rate(count((r) => r.greedyWins))}',
  );
  final bySeed = {for (final r in graded) r.seed: r};
  for (final MapEntry(key: difficulty, value: seeds) in buckets.entries) {
    final reports = [for (final s in seeds) ?bySeed[s]];
    print(
      '  ${difficulty.name.padRight(6)} ${seeds.length} seeds, '
      'natural share ${rate(count((r) => r.difficulty == difficulty))}'
      '${_averages(reports)}',
    );
  }
}

String _averages(List<SeedReport> reports) {
  if (reports.isEmpty) return '';
  double avg(int Function(SeedReport) value) =>
      reports.fold(0, (sum, r) => sum + value(r)) / reports.length;
  final casual = avg((r) => r.casualWins) / TriPeaksGrading.casualGames;
  return ', casual player wins ${(casual * 100).toStringAsFixed(1)}%, '
      'solver nodes avg ${avg((r) => r.nodes).round()}';
}

/// Prints the distribution of grading metrics over seeds 1..[count].
Future<void> _printStats(int count) async {
  final workers = Platform.numberOfProcessors;
  final stopwatch = Stopwatch()..start();
  final reports = <SeedReport>[];
  for (var next = 1; next <= count; next += workers * _chunkSize) {
    final batch = await Future.wait([
      for (var w = 0; w < workers; w++) _spawn(next + w * _chunkSize),
    ]);
    reports.addAll(batch.expand((r) => r).where((r) => r.seed <= count));
  }
  final buckets = {
    for (final d in TriPeaksDifficulty.values)
      d: [
        for (final r in reports)
          if (r.difficulty == d) r.seed,
      ],
  };
  _printSummary(reports, buckets);
  if (reports.any((r) => r.status == SolveStatus.solved && !r.verified)) {
    print('  SOME SOLUTIONS DO NOT REPLAY');
  }
  String percentiles(List<num> values) {
    values.sort();
    String at(double p) => '${values[((values.length - 1) * p).round()]}';
    return 'p10 ${at(.1)}, p25 ${at(.25)}, p50 ${at(.5)}, p75 ${at(.75)}, '
        'p90 ${at(.9)}, max ${values.last}';
  }

  for (final status in SolveStatus.values) {
    final nodes = [
      for (final r in reports)
        if (r.status == status) r.nodes,
    ];
    if (nodes.isEmpty) continue;
    print('  solver nodes when ${status.name}: ${percentiles(nodes)}');
  }
  for (final greedy in [true, false]) {
    final wins = [
      for (final r in reports)
        if (r.status == SolveStatus.solved && r.greedyWins == greedy)
          r.casualWins,
    ];
    if (wins.isEmpty) continue;
    print(
      '  casual wins (of ${TriPeaksGrading.casualGames}) when greedy '
      '${greedy ? 'wins ' : 'loses'}: ${percentiles(wins)}',
    );
  }
  print('  ${_seconds(stopwatch)}');
}

String _percent(int part, int total) =>
    '${(100 * part / total).toStringAsFixed(1)}%';

String _seconds(Stopwatch stopwatch) =>
    '${(stopwatch.elapsedMilliseconds / 1000).toStringAsFixed(1)} s';
