#!/usr/bin/env bash
# Runs every test file of test/ in one `flutter test` process: one compile
# instead of one per file (much faster on the 4-CPU CI runner).
# Usage: scripts/test_bundle.sh [extra flutter test args, e.g. --no-pub]
set -euo pipefail

cd "$(dirname "$0")/.."

# Outside test/, so a plain `flutter test` does not run every test twice.
bundle=build/test_bundle/all_test.dart
mkdir -p "$(dirname "$bundle")"
files=()
while IFS= read -r file; do files+=("$file"); done < <(
  cd test && find . -name '*_test.dart' | sed 's|^\./||' | sort
)
{
  echo "// Generated by scripts/test_bundle.sh: every test file in one compile."
  echo "import 'package:flutter_test/flutter_test.dart';"
  echo
  for i in "${!files[@]}"; do
    echo "import '../../test/${files[$i]}' as t$i;"
  done
  echo
  echo 'void main() {'
  for i in "${!files[@]}"; do
    echo "  group('${files[$i]}', t$i.main);"
  done
  echo '}'
} >"$bundle"

flutter test "$@" "$bundle"
